#!/bin/sh

# script/tests/go-race: Run go tests

set -e

cd "$(dirname "$0")/../.."

export DATABASE_URL="postgres://postgres@localhost/postgres?sslmode=disable"

[ -z "$CI" ] || {
  cd "$GOPATH/src/github.com/blendle/pg2kafka"
  export DATABASE_URL="postgres://postgres@localhost/test1?sslmode=disable"
}

go test ./...
