#!/bin/sh

# script/tests/gometalinter: Run linters and static analysis

set -e

cd "$(dirname "$0")/../.."

export DATABASE_URL="postgres://postgres@localhost/postgres?sslmode=disable"

[ -z "$CI" ] || {
  cd "$GOPATH/src/github.com/blendle/pg2kafka"
  export DATABASE_URL="postgres://postgres@localhost/test2?sslmode=disable"
}

matches=$(grep \
  --ignore-case \
  --recursive \
  --exclude-dir vendor \
  '^// [a-z]* \.\.\.$' . || true)

if [ -n "$matches" ]; then
  >&2 echo "Invalid code comments detected:"
  >&2 echo
  >&2 echo "$matches"
  >&2 echo
  exit 1
fi

# concurrency is set to 1 due to conrrent linters manipulating the DB,
# which won't work, yet.
gometalinter \
  --vendor \
  --tests \
  --aggregate \
  --line-length=100 \
  --deadline=300s \
  --concurrency=1 \
  --exclude='.*_test\.go:.*is unused \(U1000\)' \
  --enable-all \
  --disable=safesql \
  ./...
