#!/bin/sh

# Add 'pg2kafka_test' as Postgres user and DB
# (prevents: 'Exception OperationalError: FATAL:  role "xxx" does not exist')
DB_USER="pg2kafka_test"
DB_NAME="pg2kafka_test"
psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1 || createuser --superuser $DB_USER
psql postgres -tAc "SELECT 1 FROM pg_database WHERE datname = '$DB_NAME'" | grep -q 1 || psql -U postgres -c "CREATE DATABASE $DB_NAME"
