#!/bin/sh

# script/cibuild: Compile application binary on CI environment.

set -aeu

cd "$(dirname "$0")/.."

script/cisetup

workspace="$PWD"
cd "$GOPATH/src/github.com/blendle/pg2kafka"

script/build

cp "pg2kafka" "$workspace"
